return {
	[1000] = {
		cardid = 10001,
		name = "初始等级变化",
		quality = 1,
		category = "随机事件",
		teamType = "全阵营",
		maxLevel = 1,
		descLevel1 = "开局所有超弦体4级，晶源体5级",
	},
	[1001] = {
		cardid = 10002,
		name = "第一张金卡满级",
		quality = 1,
		category = "随机事件",
		teamType = "全阵营",
		maxLevel = 1,
		descLevel1 = "所有人抽到的第一张能升级的金卡直接满级",
	},
	[1002] = {
		cardid = 10003,
		name = "解锁终极技能",
		quality = 1,
		category = "随机事件",
		teamType = "全阵营",
		maxLevel = 1,
		descLevel1 = "所有人默认解锁终极技能",
	},
	[1003] = {
		cardid = 10004,
		name = "保留等级",
		quality = 1,
		category = "随机事件",
		teamType = "全阵营",
		maxLevel = 1,
		descLevel1 = "本局超弦体被击败变成晶源体后，保留等级",
	},
	[1005] = {
		cardid = 10005,
		name = "所有超弦体自带【猎人日记】，所有晶源体自带【恶意收购】",
		quality = 1,
		category = "随机事件",
		teamType = "全阵营",
		maxLevel = 1,
		descLevel1 = "所有超弦体自带【猎人日记】，所有晶源体自带【恶意收购】",
	},
	[1006] = {
		cardid = 10006,
		name = "所有超弦体自带【谁是大王】，所有晶源体自带【谁是小丑】",
		quality = 1,
		category = "随机事件",
		teamType = "全阵营",
		maxLevel = 1,
		descLevel1 = "所有超弦体自带【谁是大王】，所有晶源体自带【谁是小丑】",
	},
	[1007] = {
		cardid = 10007,
		name = "所有超弦体只能抽到【无中生有】，所有晶源体只能抽到【混沌之选】",
		quality = 1,
		category = "随机事件",
		teamType = "全阵营",
		maxLevel = 1,
		descLevel1 = "所有超弦体只能抽到【无中生有】，所有晶源体只能抽到【混沌之选】",
	},
	[1008] = {
		cardid = 10008,
		name = "本局决战时间固定为1分钟",
		quality = 1,
		category = "随机事件",
		teamType = "全阵营",
		maxLevel = 1,
		descLevel1 = "本局决战时间固定为1分钟",
	},
	[1009] = {
		cardid = 10009,
		name = "问了吗",
		quality = 1,
		category = "随机事件",
		teamType = "全阵营",
		maxLevel = 1,
		descLevel1 = "问了，令和信的初始伤害提升50%",
	},
	[1010] = {
		cardid = 10010,
		name = "加速",
		quality = 1,
		category = "随机事件",
		teamType = "全阵营",
		maxLevel = 1,
		descLevel1 = "本局随时间获得的经验值增加",
	},
}
