return {
	['警探'] = {
		['警探-青绿'] = {
			id = 10101009,
			quality = 3,
			get = { "活动" },
			BabloCrystals = "",
			Basestrings = "",
			desc = "警探的个性化定制涂装,这款涂装诉说着米雪儿相信的一个真理。",
			remark = "移动端公测预约奖励",
		},
		['警探-炽红'] = {
			id = 10101011,
			quality = 3,
			get = { "活动" },
			BabloCrystals = "",
			Basestrings = "",
			desc = "警探的个性化定制涂装,这款涂装诉说着米雪儿相信的一个真理。",
			remark = "移动端公测预约奖励",
		},
		['警探-初心'] = {
			id = 10101012,
			quality = 3,
			get = { "活动" },
			BabloCrystals = "",
			Basestrings = "",
			desc = "警探的个性化定制涂装,这款涂装诉说着米雪儿相信的一个真理。",
			remark = "移动端公测预约奖励",
		},
		['警探-碳灰'] = {
			id = 10101030,
			quality = 3,
			get = { "活动" },
			BabloCrystals = "",
			Basestrings = "",
			desc = "警探的个性化定制涂装,这款涂装诉说着米雪儿相信的一个真理。",
			remark = "移动端公测预约奖励",
		},
		['警探-苍翠'] = {
			id = 10101031,
			quality = 3,
			get = { "活动" },
			BabloCrystals = "",
			Basestrings = "",
			desc = "警探的个性化定制涂装,这款涂装诉说着米雪儿相信的一个真理。",
			remark = "移动端公测预约奖励",
		},
		['警探-新叶'] = {
			id = 10101034,
			quality = 3,
			get = { "活动" },
			BabloCrystals = "",
			Basestrings = "",
			desc = "警探的个性化定制涂装,这款涂装诉说着米雪儿相信的一个真理。",
			remark = "移动端公测预约奖励",
		},
		['警探-熟橙'] = {
			id = 10101029,
			quality = 3,
			get = { "活动" },
			BabloCrystals = "",
			Basestrings = "",
			desc = "警探的个性化定制涂装,这款涂装诉说着米雪儿相信的一个真理。",
			remark = "移动端公测预约奖励",
		},
		['警探-明橙'] = {
			id = 10101035,
			quality = 3,
			get = { "活动" },
			BabloCrystals = "",
			Basestrings = "",
			desc = "警探的个性化定制涂装,这款涂装诉说着米雪儿相信的一个真理。",
			remark = "移动端公测预约奖励",
		},
		['警探-深蓝'] = {
			id = 10101033,
			quality = 3,
			get = { "活动" },
			BabloCrystals = "",
			Basestrings = "",
			desc = "警探的个性化定制涂装,这款涂装诉说着米雪儿相信的一个真理。",
			remark = "移动端公测预约奖励",
		},
		['警探-浅蓝'] = {
			id = 10101032,
			quality = 3,
			get = { "活动" },
			BabloCrystals = "",
			Basestrings = "",
			desc = "警探的个性化定制涂装,这款涂装诉说着米雪儿相信的一个真理。",
			remark = "移动端公测预约奖励",
		},
	},
	['彩绘'] = {
		['夏日茄饮'] = {
			id = 10301057,
			quality = 3,
			get = { "赛季奖励" },
			BabloCrystals = "",
			Basestrings = "",
			desc = "长廊绘制所定制出品的“夏日茄饮”涂装，新鲜的茄果如少女般纯净，给焦灼的战场带来清热的微酸。",
			remark = "移动端第1赛季聚变质子段位奖励",
		},
	},
}